{{- if .Values.sso }}
apiVersion: v1
kind: Secret
metadata:
  name: argo-server-sso
type: Opaque
data:
  client-id: {{ .Values.sso.clientId | b64enc }}
  client-secret: {{ .Values.sso.clientSecret | b64enc }}
{{- end }}
