apiVersion: v2
name: powerdns
description: powerdns
type: application
version: 1.0.5
appVersion: 4.7.3
dependencies:
  - name: postgresql-ha
    version: 11.7.2
    repository: oci://registry-1.docker.io/bitnamicharts
