{{- if $.Values.release }}
{{- if eq $.Values.release.type "statefulset" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-%s" $.Release.Name $.Values.release.name }}
  labels:
    release: {{ printf "%s-%s" $.Release.Name $.Values.release.name }}
    {{- range $k, $v := $.Values.release.labels }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- if $.Values.release.annotations }}
  annotations:
    {{- range $k, $v := $.Values.release.annotations }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ $.Values.release.replicaCount }}
  selector:
    matchLabels:
      release: {{ printf "%s-%s" $.Release.Name $.Values.release.name }}
  serviceName: {{ printf "%s-%s" $.Release.Name $.Values.release.name }}
  template:
    metadata:
      labels:
        release: {{ printf "%s-%s" $.Release.Name $.Values.release.name }}
        {{- range $k, $v := $.Values.release.labels }}
        {{ $k }}: {{ tpl $v $ }}
        {{- end }}
      {{- if $.Values.release.annotations }}
      annotations:
        {{- range $k, $v := $.Values.release.annotations }}
        {{ $k }}: {{ tpl $v $ | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- if $.Values.release.imagePullSecrets }}
      imagePullSecrets:
        {{- range $imagePullSecret := $.Values.release.imagePullSecrets }}
        - name: {{ tpl $imagePullSecret.name $ }}
        {{- end }}
      {{- end }}
      {{- if $.Values.release.hostNetwork }}
      hostNetwork: {{ $.Values.release.hostNetwork }}
      {{- end }}
      {{- if $.Values.release.nodeSelector }}
      nodeSelector: {{ $.Values.release.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if $.Values.release.tolerations }}
      tolerations: {{ $.Values.release.tolerations | toYaml | nindent 8 }}
      {{- end }}
      volumes:
        - name: tz
          configMap:
            name: "{{ printf "%s-%s" $.Release.Name $.Values.release.name }}-tz"
        {{- range $volume := $.Values.release.volumes }}
        {{- if $volume.emptyDir }}
        - name: {{ $volume.name }}
          emptyDir: {{ $volume.emptyDir | toYaml | nindent 12 }}
        {{- end }}
        {{- if $volume.persistentVolumeClaim }}
        - name: {{ $volume.persistentVolumeClaim.claimName }}
          persistentVolumeClaim:
            claimName: "{{ printf "%s-%s" $.Release.Name $.Values.release.name }}-{{ $volume.persistentVolumeClaim.claimName }}"
        {{- end }}
        {{- if $volume.configMap }}
        - name: {{ $volume.name }}
          configMap:
            name: "{{ printf "%s-%s" $.Release.Name $.Values.release.name }}-{{ $volume.configMap.name }}"
            defaultMode: "{{ $volume.defaultMode | default '420' }}"
        {{- end }}
        {{- if $volume.secret }}
        - name: {{ $volume.name }}
          secret:
            secretName: "{{ printf "%s-%s" $.Release.Name $.Values.release.name }}-{{ $volume.secret.secretName }}"
            defaultMode: "{{ $volume.defaultMode | default '420' }}"
        {{- end }}
        {{- if $volume.hostPath }}
        - name: {{ $volume.name }}
          hostPath: {{ $volume.hostPath | toYaml | nindent 12 }}
        {{- end }}
        {{- end }}
      containers:
      {{- range $container := $.Values.release.containers }}
        - name: {{ $container.name }}
          image: {{ tpl $container.image $ }}
          imagePullPolicy: {{ $container.pullPolicy | default "IfNotPresent" }}
          {{- if $container.command }}
          command: {{ $container.command | toYaml | nindent 12 }}
          {{- end }}
          {{- if $container.args }}
          args: {{ $container.args | toYaml | nindent 12 }}
          {{- end }}
          {{- if $container.env }}
          env: {{ $container.env | toYaml | nindent 12 }}
          {{- end }}
          {{- if $container.envFrom }}
          envFrom: # optional
            {{- range $envRefs := $container.envFrom  }}
            {{- range $envRef, $refData := $envRefs  }}
            - {{ $envRef }}:
                name: "{{ printf "%s-%s" $.Release.Name $.Values.release.name }}-{{ $refData.name }}"
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if $container.ports }}
          ports: {{ $container.ports | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tz
              mountPath: /etc/localtime
              subPath: {{ $.Values.release.timezone }}
            {{- if $container.volumeMounts }}
            {{- $container.volumeMounts | toYaml | nindent 12 }}
            {{- end }}
          {{- if $container.resources }}
          resources:
            {{- if $container.resources.requests }}
            requests: {{ $container.resources.requests | toYaml | nindent 14 }}
            {{- end }}
            {{- if $container.resources.limits }}
            limits: {{ $container.resources.limits | toYaml | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- if $container.readinessProbe }}
          readinessProbe: {{ $container.readinessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if $container.livenessProbe }}
          livenessProbe: {{ $container.livenessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if $container.securityContext }}
          securityContext: {{ $container.securityContext | toYaml | nindent 12 }}
          {{- end }}
      {{- end }}
  {{- if $.Values.release.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- range $volumeTemplate := $.Values.release.volumeClaimTemplates }}
    - metadata:
        name: {{ $volumeTemplate.name }}
        labels:
          release: {{ printf "%s-%s" $.Release.Name $.Values.release.name }}
          {{- range $k, $v := $volumeTemplate.labels }}
          {{ $k }}: {{ tpl $v $ }}
          {{- end }}
        {{- if $volumeTemplate.annotations }}
        annotations: {{ $volumeTemplate.annotations | toYaml | nindent 10 }}
        {{- end }}
      spec: {{ $volumeTemplate.spec | toYaml | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
